apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: development
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 381743254372.dkr.ecr.us-west-1.amazonaws.com/meetup:{image_tag}
        ports:
        - containerPort: 9001
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "400m"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service-loadbalancer
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001

---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: backendhpa
   namespace: development
spec:
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 7
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
