apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontenddeployment
 namespace: development
spec:
 replicas: 2
 selector:
  matchLabels:
   apptype: web
   env: dev
 template:
  metadata:
    name: frontendtemp
    labels:
      apptype: web
      env: dev
  spec:
   containers:
   - image: 381743254372.dkr.ecr.us-west-1.amazonaws.com/meetup:frontend
     name: frontend
     imagePullPolicy: Always
     ports:
     - name: frontendapp
       containerPort: 80
       protocol: TCP
     resources:
       requests:
        memory: "200Mi"
        cpu: "200m"
       limits:
         memory: "300Mi"
         cpu: "400m"
