apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 namespace: development
spec:
 replicas: 2
 selector:
  matchLabels:
   apptype: frontend
   env: dev
 template:
  metadata:
    name: frontend
    labels:
      apptype: frontend
      env: dev
  spec:
   containers:
   - image: 381743254372.dkr.ecr.us-west-1.amazonaws.com/meetup:frontend
     name: frontendcon
     imagePullPolicy: Always
     ports:
     - name: frontendport
       containerPort: 80
       protocol: TCP
     resources:
       requests:
        memory: "1000Mi"
        cpu: "1000m"
       limits:
         memory: "2000Mi"
         cpu: "2000m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 namespace: development
spec:
 replicas: 2
 selector:
  matchLabels:
   apptype: backend
   env: dev
 template:
  metadata:
    name: backend
    labels:
      apptype: backend
      env: dev
  spec:
   containers:
   - image: 381743254372.dkr.ecr.us-west-1.amazonaws.com/meetup:backend
     name: backendcon
     imagePullPolicy: Always
     ports:
     - name: backendport
       containerPort: 9001
       protocol: TCP
     resources:
       requests:
        memory: "1000Mi"
        cpu: "1000m"
       limits:
         memory: "2000Mi"
         cpu: "2000m"
