apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 namespace: development
spec:
 replicas: 2
 selector:
  matchLabels:
   apptype: frontend
   env: dev
 template:
  metadata:
    name: frontend
    labels:
      apptype: frontend
      env: dev
  spec:
   containers:
  #  - image: 381743254372.dkr.ecr.us-west-1.amazonaws.com/meetup:{image_tag}
   - image: sudarshanlnx/2022sundayweb:v1
     name: frontendcon
     imagePullPolicy: Always
     ports:
     - name: frontendport
       containerPort: 80
       protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
 name: frontendsvc
 namespace: development
spec:
 ports:
 - name: frontendport
   port: 80
   targetPort: 80
   protocol: TCP
 selector:
  apptype: frontend
  env: dev


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: meetupingress
   namespace: development
spec:
   rules:
   - host: "meetup-swashikan.airesearch.lsac-dev.com"
     http:
       paths:
       - path: "/"
         pathType: Prefix
         backend:
           service:
             name: frontendsvc
             port:
              number: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: frontendhpa
   namespace: development
spec:
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
