apiVersion: v1
kind: Service
metadata:
 name: websvc
 namespace: development
spec:
 type: LoadBalancer
 ports:
 - name: frontend
   port: 80
   targetPort: 80
   protocol: TCP
 selector:
  apptype: web
  env: dev
