apiVersion: v1
kind: Service
metadata:
 name: frontendsvc
 namespace: development
spec:
 ports:
 - name: apache
   port: 80
   protocol: TCP
 type: LoadBalancer
 selector:
  apptype: frontend
  env: dev

---

apiVersion: v1
kind: Service
metadata:
 name: backendsvc
 namespace: development
spec:
 ports:
 - name: apache
   port: 9001
   protocol: TCP
 type: LoadBalancer
 selector:
  apptype: backend
  env: dev
